### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by BenjaminSemah** [clintonjosephs/conference_website#2]
- Consider using a <ul> in place of <div> for the lists.
- Every page should have just 1 h1 tag.
- Width and height attributes in partners images should be moved to CSS.
- Change the Facebook logo so that the icon doesn’t blend totally with the background.
- Merge mobile menu and desktop menu as 1 menu.

**Comment by clintonjosephs** [comment]
Thank you for your review, all changes has be reflected as suggested! Cheers
